/* confdefs.h */
#define PACKAGE_NAME "libffi"
#define PACKAGE_TARNAME "libffi"
#define PACKAGE_VERSION "3.99999"
#define PACKAGE_STRING "libffi 3.99999"
#define PACKAGE_BUGREPORT "http://github.com/libffi/libffi/issues"
#define PACKAGE_URL ""
#define PACKAGE "libffi"
#define VERSION "3.99999"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define SIZEOF_SIZE_T 8
#define HAVE_SYS_MMAN_H 1
#define HAVE_MMAP 1
#define HAVE_MKOSTEMP 1
#define HAVE_MMAP_FILE 1
#define HAVE_MMAP_ANON 1
#define STDC_HEADERS 1
#define HAVE_MEMCPY 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 16
#define HAVE_LONG_DOUBLE 1
#define HAVE_AS_CFI_PSEUDO_OP 1
#define HAVE_AS_X86_PCREL 1
#define SYMBOL_UNDERSCORE 1
#define FFI_MMAP_EXEC_WRIT 1
#define EH_FRAME_FLAGS "aw"
